repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: pretty-format-json
        args: ['--autofix']
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        types: [file, python]
        args: [--max-line-length=88, --max-complexity=12, --extend-ignore=E203]
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
## UNTESTED
-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.7.0
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff-lint
        entry: sqlfluff lint
        language: python
        description: 'Lints sql files with `SQLFluff`'
        types: [sql]
        require_serial: true
        additional_dependencies: []
      - id: sqlfluff-fix
        name: sqlfluff-fix
        # Needs to use "--force" to disable confirmation
        # By default all the rules are applied
        entry: sqlfluff fix --force
        language: python
        description: 'Fixes sql lint errors with `SQLFluff`'
        types: [sql]
        require_serial: true
        additional_dependencies: []
